AllCops:
  Exclude:
    - DerivedData/**/*
    - Pods/**/*
    - vendor/**/*
  NewCops: enable

Metrics/BlockLength:
  Exclude: &fastfiles
    - fastlane/Fastfile
    - fastlane/lanes/*.rb
    # `Rakefile` should be part of the `&fastfiles` group, but the same settings apply to it, too, so that seems fitting
    - Rakefile

Metrics/MethodLength:
  Max: 30
  Exclude: *fastfiles

Layout/LineLength:
  Max: 180
  Exclude: *fastfiles

Layout/EmptyLines:
  Exclude: *fastfiles

Style/AsciiComments:
  Exclude: *fastfiles

Naming/FileName:
  Exclude:
    - fastlane/Matchfile
